// Code generated by mockery v2.53.6. DO NOT EDIT.

package notify

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// mockMetricsRecorder is an autogenerated mock type for the metricsRecorder type
type mockMetricsRecorder struct {
	mock.Mock
}

// RecordProcessed provides a mock function with given fields: ctx, start, err
func (_m *mockMetricsRecorder) RecordProcessed(ctx context.Context, start time.Time, err error) {
	_m.Called(ctx, start, err)
}

// RecordReceived provides a mock function with given fields: ctx, count
func (_m *mockMetricsRecorder) RecordReceived(ctx context.Context, count int) {
	_m.Called(ctx, count)
}

// newMockMetricsRecorder creates a new instance of mockMetricsRecorder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockMetricsRecorder(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockMetricsRecorder {
	mock := &mockMetricsRecorder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
