services:
  uni-logium-svc:
    build: .
    container_name: uni-logium-svc
    env_file: .env
    ports:
      - "${EXTERNAL_HTTP_PORT}:${INTERNAL_HTTP_PORT}"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - SQS_QUEUE_URL=${SQS_QUEUE_URL}
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://uni-otel-collector:4318
      - OTEL_SERVICE_NAME=uni-logium-svc

networks:
  default:
    name: uni-net
    external: true
